/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as teamsManagerSol from "./TeamsManager.sol";
export type { teamsManagerSol };
export type { Administrable } from "./Administrable";
export type { AdvancedGovernance } from "./AdvancedGovernance";
export type { MockERC20 } from "./MockERC20";
