/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMemeToken,
  IMemeTokenInterface,
} from "../../../contracts/TeamsManager.sol/IMemeToken";

const _abi = [
  {
    inputs: [],
    name: "getUri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMemeToken__factory {
  static readonly abi = _abi;
  static createInterface(): IMemeTokenInterface {
    return new Interface(_abi) as IMemeTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMemeToken {
    return new Contract(address, _abi, runner) as unknown as IMemeToken;
  }
}
